server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/event_booking

# Redis Configuration
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# JWT Configurations (256-bit key for HMAC)
jwt.secret=9Y1aB5mE9tRzQv8sW3xP0uL6kF4hC2dG7nJ5iY8oP1wM4vS7eR2tA0yB8cX5zK3w
jwt.expiration=86400000

# Logging Level
logging.level.com.event.booking=INFO
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.data.redis=INFO
